@c1 = Category.create(name: 'Vocabulary', color: "#2196f3", description: "Brush up on some vocabulary with a variety of topics including names of animals, fruits and more!")
@c2 = Category.create(name: 'Verb Introduction', color: "#d81b60", description: "Take on learning the simple verbs and suffixes in French to start chaining your nouns together!")
@c3 = Category.create(name: 'Simple Phrases', color: "#f44336", description: "Learn the basics of writing sentences in French! Learn how to say simple sentences like: How are you today? and I like the colour red! \n")
@c4 = Category.create(name: 'Asking Questions', color: "#009688", description: "What?")
@c5 = Category.create(name: 'Reading', color: "#8bc34a", description: "You're reading right now")
@c6 = Category.create(name: 'ER, IR, RE Verbs', color: "#fbc02d", description: "Learn to separate verbs you know into these 3 different types and when to use each")

Topic.create(name: "Animals", category_id: @c1.id, description: "Study the names of your favourite animals using interactive flash cards and then try out your skills in game mode!")
Topic.create(name: "Fruits", category_id: @c1.id,  description: "Study the names of your favourite fruits using interactive flash cards and then try out your skills in game mode!")
Topic.create(name: "Vegetables", category_id: @c1.id, description: "Study the names of your favourite vegetables using interactive flash cards and then try out your skills in game mode!")
Topic.create(name: "Colours", category_id: @c1.id, description: "Study the names of your favourite colours using interactive flash cards and then try out your skills in game mode!")
Topic.create(name: "Clothing", category_id: @c1.id, description: "Study the names of your favourite clothing using interactive flash cards and then try out your skills in game mode!")
Topic.create(name: "Weather", category_id: @c1.id, description: "Study fun weather words using interactive flash cards and then try out your skills in game mode!")

Topic.create(name: "Etre", category_id: @c2.id)
Topic.create(name: "Avoir", category_id: @c2.id)
Topic.create(name: "Aller", category_id: @c2.id)
Topic.create(name: "Faire", category_id: @c2.id)

Level.create(number: 1, topic_id: 1)
Level.create(number: 2, topic_id: 1)
Level.create(number: 3, topic_id: 1)

Level.create(number: 1, topic_id: 2)
Level.create(number: 2, topic_id: 2)
Level.create(number: 3, topic_id: 2)

Question.create(word: "Un Chien", word_image: "/dog_icon.png", english_word: "Dog", level_id: 1)
Question.create(word: "Un Chat", word_image: "/cat_icon.png", english_word: "Cat", level_id: 1)
Question.create(word: "Un Lion", word_image: "/lion_icon.png", english_word: "Lion", level_id: 1)
Question.create(word: "Un Ours", word_image: "/bear_icon.png", english_word: "Bear", level_id: 1)
Question.create(word: "Une Souris", word_image: "/mouse_icon.png", english_word: "Mouse", level_id: 1)

Question.create(word: "Un Poisson", word_image: "/nemo_icon.png", english_word: "Fish", level_id: 2)
Question.create(word: "Un Cochon", word_image: "/pig_icon.png", english_word: "Pig", level_id: 2)
Question.create(word: "Un Serpent", word_image: "/snake_icon.png", english_word: "Snake", level_id: 2)
Question.create(word: "Une Tortue", word_image: "/turtle_icon.png", english_word: "Turtle", level_id: 2)
Question.create(word: "Un Zébra", word_image: "/zebra_icon.png", english_word: "Zebra", level_id: 2)

Question.create(word: "Un Poulet", word_image: "/chicken_icon.png", english_word: "Chicken", level_id: 3)
Question.create(word: "Un Mouton", word_image: "/sheep_icon.png", english_word: "Sheep", level_id: 3)
Question.create(word: "Un Cheval", word_image: "/horse_icon.png", english_word: "Horse", level_id: 3)
Question.create(word: "Une Baleine", word_image: "/whale_icon.png", english_word: "Whale", level_id: 3)
